### ISSUE TITLE
Deployment ToDo Tracker

### ISSUE THREAD

**Issue by cohoe** [cohoe/swiftarr#10]
- [ ] Redis dashboard & exporter.
- [ ] Performance test: Traefik vs Direct.
- [ ] Mount images to local directory.
- [ ] Cron backup of images.
